// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL6QypnMA02bmXscCoO2kB9pFo_v97M-A',
    appId: '1:969272556489:web:a87838effcd34530938618',
    messagingSenderId: '969272556489',
    projectId: 'flutter-project-56d54',
    authDomain: 'flutter-project-56d54.firebaseapp.com',
    storageBucket: 'flutter-project-56d54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWfsnivAqnrYvltsNznje1acN5lTTuNyE',
    appId: '1:969272556489:android:bfc00260cb6f01f0938618',
    messagingSenderId: '969272556489',
    projectId: 'flutter-project-56d54',
    storageBucket: 'flutter-project-56d54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSxBP8ME7iKMHlVvPw0VIwYR6qFpJjMJY',
    appId: '1:969272556489:ios:5b743aae8af5296d938618',
    messagingSenderId: '969272556489',
    projectId: 'flutter-project-56d54',
    storageBucket: 'flutter-project-56d54.appspot.com',
    androidClientId: '969272556489-kip6m8bfdiifoesgtbg16e0r4un0psin.apps.googleusercontent.com',
    iosClientId: '969272556489-cih1n81l4oai51ap1sd4vif5sqgkj0hg.apps.googleusercontent.com',
    iosBundleId: 'com.example.newHotelApp',
  );
}
